"""Add unique together constraint for items and users on rating table

Revision ID: 2e01c643cfd9
Revises: 7996204a40bb
Create Date: 2023-01-17 21:00:14.435945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e01c643cfd9'
down_revision = '7996204a40bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings') as batch_op:
        batch_op.create_unique_constraint(
            'unique_user_item',
            ['itemId', 'userId'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings') as batch_op:
        batch_op.drop_constraint('unique_user_item')
    # ### end Alembic commands ###
