"""Add check constraint for latlong

Revision ID: 7996204a40bb
Revises: e7c24ae46946
Create Date: 2023-01-17 19:31:54.235739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7996204a40bb'
down_revision = 'e7c24ae46946'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_items') as batch_op:
        batch_op.create_check_constraint(
            'check',
            '''
                (latitude IS NOT NULL AND longitude IS NOT NULL)
                OR (latitude IS NULL AND longitude IS NULL)
            ''',
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_items') as batch_op:
        batch_op.drop_constraint('check')
    # ### end Alembic commands ###
