"""Move description from items to ratings table

Revision ID: caa21930c35b
Revises: 6542e4d6ae68
Create Date: 2023-01-14 20:35:22.161965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa21930c35b'
down_revision = '6542e4d6ae68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating_items', 'description')
    op.add_column('ratings', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'description')
    op.add_column('rating_items', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
